# index.dump_json = "/dev/stdout"
[settings]
  # verbose = true
  # generator_mode = false
  clean_urls = true
  # caching = false

  doctype = "<!DOCTYPE html>"
  page_file_extensions = ["html"]

  build_dir = "public"
  site_dir = "third-website/build"
# https://soupault.app/reference-manual/#index-views
[index.fields.computer-of-the-future]
  selector = "p:has(a)"
  # extract_attribute = ":text()"
  # fallback_to_content = true
[index.views.computer-of-the-future]
  index_selector = "a[href=\"/computer-of-the-future\"]"
  # index_selector = "computer-of-the-future"
  index_processor = "cat >/dev/tty"

