#!/usr/bin/env bb
(ns ci.generate-ci 
  (:require
   [babashka.fs :as fs]
   [clj-yaml.core :as yaml]
   [clojure.string :as str]))

(defn escape-shell
  "the world's WORST shell escaper"
  [s]
  (str "'" (str/escape s {\' "'\\''"}) "'"))

(defn join-shell
  "EVEN WORSE than the last one"
  [xs]
  (str/join " " (map escape-shell xs)))

(def dst ".woodpecker/test.yaml")

(def pipeline-cache "cache")
(def clj-config (str pipeline-cache "/clj-config"))
(def env
  {:CLJ_CONFIG clj-config
   :GITLIBS (str pipeline-cache "/gitlibs")})
(def deps
  {:mvn/local-repo (str pipeline-cache "/m2")})

(defn clj
  ([args] (clj "clojure" args))
  ([clojure args]
   (let [deps (binding [*print-namespace-maps* false] (pr-str deps))]
    ; (str "bash -x $(which clojure) "
    ; -Sdeps is hard to pass to the integration test runner because it contains whitespace.
    ; for now, hack it with symlinks (see below).
    (join-shell (concat [clojure #_"-Sdeps" #_deps "-J-Dclojure.main.report=stderr"] args)))))

(def clj-version "trixie")
; https://hub.docker.com/_/clojure
(def clj-image (str "clojure:tools-deps-" clj-version "-slim"))
(def graal-version 25)
; https://github.com/graalvm/container/pkgs/container/jdk-community
(def graal-image (str "ghcr.io/graalvm/native-image-community:" graal-version))

(def setup-m2
  ["rm -rf ~/.m2"
   "mkdir -p cache/m2"
   "ln -Tsf $(realpath cache/m2) ~/.m2"])

(def config
  {:when
   {:event ["push" "pull_request"]}
   :steps [{:name :prepare
     :image clj-image
     :environment env
     :commands
     (concat setup-m2
      [(clj ["-P" "-M:test"])
       ; uses :deps, not :extra-deps, so needs to be separate
       (clj ["-P" "-M:build"])
       "git config --global --add safe.directory $(realpath .)"
       (clj ["-T:build" "manifest" ":include-untracked" "true"])
       (str "ci/install-clj.sh " pipeline-cache)])}

    {:name :unit
     :image clj-image
     :depends_on [:prepare]
     :environment env
     :commands 
     (concat setup-m2 [(clj ["-M:test" "--skip" ":process"])])}

    {:name :integration
     :image graal-image
     :depends_on [:prepare]
     :environment env
     :commands
     (concat
       setup-m2
       ["export LC_ALL=C.utf-8"
        "microdnf install -y dnf dnf-plugins-core >/dev/null"
        "dnf config-manager --enable ol10_codeready_builder"
        "dnf install nodejs npm git python3-pygments --quiet"
        "npm install -g --no-fund sass"
        "git config --global --add safe.directory $(realpath .)"
        (str "ci/run-integration-tests.sh "
             (clj (str pipeline-cache "/bin/clojure") []))])}]})

(def file (fs/relativize (System/getProperty "user.dir") *file*))
(def gen-comment (str "## Generated by " file " ##"))
(spit dst (str gen-comment "\n" (yaml/generate-string config)))
