#!/usr/bin/env bb
(ns ci.generate-ci 
  (:require
   [babashka.fs :as fs]
   [clj-yaml.core :as yaml]
   [clojure.string :as str]))

(defn escape-shell
  "the world's WORST shell escaper"
  [s]
  (str "'" (str/escape s {\' "'\\''"}) "'"))

(defn join-shell
  "EVEN WORSE than the last one"
  [xs]
  (str/join " " (map escape-shell xs)))

(def woodpecker-path ".woodpecker/test.yaml")
(def circleci-path ".circleci/config.yml")

(def pipeline-cache "cache")
(def clj-config (str pipeline-cache "/clj-config"))
(def env
  {:CLJ_CONFIG clj-config
   :GITLIBS (str pipeline-cache "/gitlibs")})
(def deps
  {:mvn/local-repo (str pipeline-cache "/m2")})

(defn clj
  ([args] (clj "clojure" args))
  ([clojure args]
   (let [deps (binding [*print-namespace-maps* false] (pr-str deps))]
    ; (str "bash -x $(which clojure) "
    ; -Sdeps is hard to pass to the integration test runner because it contains whitespace.
    ; for now, hack it with symlinks (see below).
    (join-shell (concat [clojure #_"-Sdeps" #_deps "-J-Dclojure.main.report=stderr"] args)))))

(def clj-version "trixie")
; https://hub.docker.com/_/clojure
(def clj-image (str "clojure:tools-deps-" clj-version "-slim"))
(def graal-version 25)
; https://github.com/graalvm/container/pkgs/container/jdk-community
(def graal-image (str "ghcr.io/graalvm/native-image-community:" graal-version))

(def setup-m2
  ["rm -rf ~/.m2"
   "mkdir -p cache/m2"
   "ln -Tsf $(realpath cache/m2) ~/.m2"])

; TODO: {:windows job :macos job :linux job} switcher
; TODO: need a way to distinguish that from the job; maybe whether it has :name or not
(def jobs
  [{:name :prepare
    :image clj-image
    :environment env
    :commands
    (concat setup-m2
            [(clj ["-P" "-M:test"])
             ; uses :deps, not :extra-deps, so needs to be separate
             (clj ["-P" "-M:build"])
             "git config --global --add safe.directory $(realpath .)"
             (clj ["-T:build" "manifest" ":include-untracked" "true"])
             (str "ci/install-clj.sh " pipeline-cache)])}

   {:name :unit
    :image clj-image
    :depends_on [:prepare]
    :environment env
    :commands 
    (concat setup-m2 [(clj ["-M:test" "--focus" ":unit"])])}

   {:name :integration
    :image graal-image
    :depends_on [:prepare]
    :environment env
    :commands
    (concat
      setup-m2
      ["export LC_ALL=C.utf-8"
       "microdnf install -y dnf dnf-plugins-core >/dev/null"
       "dnf config-manager --enable ol10_codeready_builder"
       "dnf install ninja-build nodejs npm git python3-pygments --quiet"
       "npm install -g --no-fund sass"
       "git config --global --add safe.directory $(realpath .)"
       (str "ci/run-integration-tests.sh "
            (clj (str pipeline-cache "/bin/clojure") []))])}])

(def woodpecker
  {:when
   {:event ["push" "pull_request"]}
   :steps jobs})

(def circle-cache-key
  "v1-dependencies-{{ checksum \"deps.edn\" }}")

(defn with-cache [key paths steps]
  (concat
    [:checkout
     {:restore_cache
      {:keys key}}]
    steps
    [{:save_cache
      {:paths paths
       :key key}}]))

(defn ->circle [job]
  (let [steps (for [command (:commands job)]
                {:run command})
        name (:name job)]
    {(:name job)
     {:docker [(select-keys job [:image])]
      :environment (:environment job)
      :steps (if (= :prepare name)
               (with-cache circle-cache-key [pipeline-cache] steps)
               steps)}}))

(def circleci
  {:version 2.1
   :jobs (apply merge (map ->circle jobs))
   :workflows
   {:test
    {:jobs
     (for [job jobs]
       (if-let [dep (:depends_on job)]
         {(:name job) {:requires dep}}
         (:name job)))}}})

(def file (fs/relativize (System/getProperty "user.dir") *file*))
(def gen-comment (str "## Generated by " file " ##\n"))

(defn write-yaml [path config]
  (spit path (str gen-comment (yaml/generate-string config))))

(write-yaml woodpecker-path woodpecker)
(write-yaml circleci-path circleci)
