(ns flower.cmd
  (:use flower.internal.utils)
  (:import
    (java.io StringWriter))
  (:require
    [clojure.data.json :as json]
    [clojure.string :as str]
    [clojure.set :refer [union]]
    [babashka.fs :as fs]
    [jq.api :as jq]
    [flower.reflect]
    [flower.frontmatter :refer [split-frontmatter]]
    [flower.eval :as eval]))

(defn- load-meta [f]
  (let [content (-> f fs/file slurp)
        split (split-frontmatter {:filename f :content content})]
   [(str f) (:frontmatter split)]))

(defn- load-all-meta [dir]
  (let [paths (fs/glob dir "**")
        files (filter #(not (fs/directory? %)) paths)]
    (into {} (map load-meta files))))

; meta-build system

(defn configure
  "Run `build.clj` to generate a build.ninja and save the output to disk."
  []
  (let [in (str *site* "/build.clj")
        out (str *site* "/build.ninja")
        ninja-writer (new StringWriter)
        page-meta (load-all-meta "pages")
        ; TODO: every time we hard-code a dir it makes things unconfigurable, figure out what to do
        template-meta (load-all-meta "templates")
        frontmatter {:pages page-meta :templates template-meta}
        dst (fs/path out)]
    (binding [flower.reflect/*ninja* ninja-writer
              flower.reflect/*frontmatter* frontmatter]
      (let [cx (eval/create-fs-cx in)
            embedded (str "(do" (slurp in) ")")
            lisp (eval/parse-string cx embedded)]
        (eval/eval-form cx embedded lisp)))
    (->> ninja-writer str .getBytes (fs/write-bytes dst))))

; template embedding
; TODO: this should happen in transformers/embed.clj
(defn embed-template
  "Given a {:content :frontmatter} page and the name of a template file,
  render `template` in context."
  [embed {:keys [template-name]}]
        ; TODO: layering violation, we shouldn't be reading this off disk.
        ; instead we should run `split-frontmatter` on the template too
        ; and then merge the two.
  (let [template-contents (-> template-name slurp)
        {template-frontmatter :frontmatter template :content}
          (split-frontmatter {:filename template-name :content template-contents})
        frontmatter (merge-deep template-frontmatter (:frontmatter embed))
        locals {'content (:content embed)
                'frontmatter frontmatter}
        embedded (eval/render-file template template-name locals)]
    {:content embedded
     :frontmatter frontmatter}))

; jq emulator

; the clojure library is buggy and the underlying java library is hideously complicated.
; rather than try to figure out their api, just parse and reserialize the string.
(defn jq
  [{:keys [data query raw-input raw-output]}]
  (let [in (if raw-input (json/write-str data) data)
        res (try (jq/execute in query)
                 (catch net.thisptr.jackson.jq.exception.JsonQueryException e
                   (fatal "failed to run jq query:" (ex-message e))))]
    (if raw-output (json/read-str res) res)))

; preprocessing

; TODO: this can just be a normal transfomer
(defn render-page
  "Preprocess and render a JSON blob"
  ([parsed {:keys [locals] :or {locals {}}}]
   (let [locals (merge-deep {'frontmatter (:frontmatter parsed)} locals)
         rendered (eval/render-file (:content parsed) (:filename parsed) locals)]
     {:content rendered
      :frontmatter (:frontmatter parsed)})))

; index preprocessing

(defn- get-meta
  [out all-meta]
  (let [orig_path (fs/path "pages" (remove-parent out))
        frontmatter (get all-meta orig_path {})]
    {:frontmatter frontmatter :path out}))

(defn render-index
  "Preprocess and render a JSON blob as an index page (i.e. with access to `pages` local)"
  [parsed]
  ; TODO: put this on disk and feed it on stdin so we don't have to trust template renderers about dependency tracking.
  ; then we can move this to flower.build
  ; TODO: pass the name of the current index as a CLI arg so we can filter it out from locals
  ; NOTE: if we want a default index.html, we cannot allow index.html to be generated by a custom command.
  ; document that you should use `include` if you want that.
  ; TODO: document that custom commands cannot generate the same output file as a page
  ; TODO: this only works for post-processed pages; fix it to run `ninja -t targets | grep ^public`
  (let [meta (load-all-meta "pages")
        ; TODO: use parse-ninja here
        out (:out (run {:out :string} "ninja -t targets rule transform"))
        ; handle empty string
        pages (if (seq out)
                (map #(update (get-meta % meta) :path remove-parent)
                     (str/split out #"\n"))
                {})]
    (render-page parsed {:locals {'pages pages}})))

(defn with-tracked-deps [dependencies f]
    (binding [flower.reflect/*dependencies* #{}]
      (let [out-map (f)
            ; TODO: should be keyed by output file so we can minimize rebuilds
            ; TODO: something is wrong here, it's not tracking file reads in templates
            all-deps (union (set dependencies) flower.reflect/*dependencies*)]
        (assoc out-map :dependencies all-deps))))

; transforming
(defn transform
  "Given a `{:content x :frontmatter y :transformer z}` map,
  run the clojure in file `:transformer` on `{:content :frontmatter}`."
  [parsed {:keys [transformer]}]
  (let [cx-opts {:bindings {'page parsed}}
        cx (eval/create-sci-cx transformer cx-opts)
        f (slurp transformer)
        ; NOTE: parse-string only parses a single form, so we have to wrap the file in `do`
        ls (str "(do " f ")")
        transformer (eval/parse-string cx ls)
        run-transform (eval/embed '(transform page))
        ; NOTE: order is important here, see https://technomancy.us/143
        lisp `(do ~transformer ~run-transform)]
    ; TODO: this discards metadata, allow the transformer to mutate metadata
    ; also allow returning just a string to inherit existing metadata
    {:content (eval/eval-form cx "" lisp)}))

(defn split-dependencies
  [parsed {:keys [depfile out-file]}]
  (let [[parsed deps] (split-map parsed :dependencies)
        joined (join-ninja (:dependencies deps))
        formatted (fmt "${out-file}: ${joined}")]
    (spit depfile formatted)
    ; NOTE: we intentionally don't write to `out-file`, build.ninja is doing that.
    parsed))

; TODO: take out-dir as an arg
(defn split-sass-dependencies
  [parsed {:keys [source-file]}]
  (let [out-dir "public"
        deps (:sources parsed)
        relative-deps (map #(fs/relativize "." (str out-dir "/" %)) deps)
        joined (join-ninja relative-deps)]
    (fmt "${source-file}: ${joined}")))

