(*
TODO: allow weird syntax in front of Ident (maybe Atom+ or something)
https://clojure.org/reference/reader
this is tricky because `#_id` needs to parse as [:Syntax "#_"], _ can't be associated with the ident
NOTE: <> are valid clojure idents, but disallowed unless they are in parentheses. too easy to write `<a name=◊x>`.

TODO: this doesn't give great errors on failure ...
*)
Start = (Text | FlowerSyntax)*
Text = #'[^◊]+'
FlowerSyntax = <'◊'> ( OuterIdent | FlowerCall | OuterComment )
(* NOTE: we disallow strings, vectors, and maps as outer forms *)
FlowerCall = ReaderSyntax? List CallTrailer
CallTrailer = <'«'> NestedRender <'»'> | !'«'
NestedRender = ( #'[^»◊]+' | FlowerSyntax )*
OuterComment = <#';[^\n]*'>
(* like Ident, but doesn't support <>.
   keep them in sync. *)
(*
Unfortunately, Java supports *none* of ID_Start, Other_ID_Start, Pattern_Syntx, or Pattern_White_Space.
Those are defined as:
- ID_Start: [\p{L}\p{Nl}\p{Other_ID_Start}-\p{Pattern_Syntax}-\p{Pattern_White_Space}].
- Other_ID_Start: actually only here for backcompat so i don't care
- Pattern_Syntax: https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=[:Pattern_Syntax=Yes:]
- Pattern_White_Space: [\t\n\v\f\r \u0085\u200e\us00f\u0028\0029]

https://www.unicode.org/reports/tr44/#XID_Start
https://www.unicode.org/reports/tr31/tr31-41.html
*)
OuterIdent = #'[-«»◊0-9\p{L}\p{Nl}%$*+!_\'?=/.&&[^\t\n\v\f\r \u0085\u200e\u000f\u2028\u2029]]+'
ReaderSyntax = #"[\;@^`~']+" | ReaderForm
ReaderForm = '#' ( #'[#:"\'_]' | Ident | & '(' )
(* keep this in sync with OuterIdent. *)
Ident = #'[-«»◊0-9\p{L}\p{Nl}<>%$*+!_\'?=/.&&[^\t\n\v\f\r \u0085\u200e\u000f\u2028\u2029]]+'
Keyword = ':' Ident
List = <'('> Sequence <')'>
Vec = <'['> Sequence <']'>
MapOrSet = <'#'?> <'{'> Sequence <'}'>
Sequence = ( <#'[\s,]+'> | #';[^\n]*\n' | Form )*
Form = (Atom | List | Vec | MapOrSet)
Atom = String | Char | Ident | Keyword | ReaderSyntax
String = '"' ( #'[^"\\]+' | #'\\.' )* '"'
Char = '\\' #'[a-zA-Z0-9*+!_\'?=/.-\\{}\[\]()]'
(* Letter = #'[a-zA-Z0-9*+!_\'?=/.-]' *)
(* Char = '\\' #'[a-zA-Z\s]' *)
(* NotStringOrChar = #'[^()\[\]#{} "]+' *)
