on:
  push:
    branches: [ dev, docs ]

concurrency:
  group: "artifacts"
  cancel-in-progress: true

jobs:
  build-native:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        exe: [flower]
        # TODO: crashes with STATUS_DLL_INIT_FAILED ????
        # see https://github.com/jyn514/flower/actions/runs/16684096005/job/47229405593#step:8:10
        # include:
        #   - os: windows-latest
        #     exe: flower.exe
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install ninja / sass / pygments
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        DEBIAN_FRONTEND=noninteractive sudo apt install -yqq ninja-build git gcc python3-pygments
        npm install -g sass

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        java-version: '25'
        distribution: 'graalvm'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Cache Clojure dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
          .cpcache
        key: ${{ runner.os }}-clojure-${{ hashFiles('**/deps.edn') }}
        restore-keys: |
          ${{ runner.os }}-clojure-

    - name: Install Clojure CLI
      uses: DeLaGuardo/setup-clojure@12.5
      with:
        cli: latest

    - name: Download dependencies
      run: clojure -J-Dclojure.main.report=stderr -P

    - name: Build native image
      run: clojure -J-Dclojure.main.report=stderr -T:build native

    - name: Test native binary
      run: |
        ls target/${{matrix.exe}}
        ./target/${{matrix.exe}} version || echo "Version check failed, but binary was created"

    - name: Build flower docs site
      if: runner.os == 'Linux'
      run: cd docs && ../target/${{matrix.exe}} build

    - name: Upload platform-specific binary
      uses: actions/upload-artifact@v4
      with:
        name: native-binary-${{ runner.os }}
        path: |
          target/${{matrix.exe}}

    - name: Setup Pages
      if: runner.os == 'Linux'
      uses: actions/configure-pages@v5

    - name: Upload flower docs site
      if: runner.os == 'Linux'
      uses: actions/upload-pages-artifact@v4
      with:
        path: ./docs/public

  deploy:
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build-native
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
