(ns expressions.constants)

(def site-title "the website of jyn")
(def site-url "https://jyn.dev")
(def site-author "jyn")
(def email "blog@jyn.dev")
(def github "jyn514")
(def linkedin "jynelson514")
(def global-desc "i write about code, and things that bring me joy, and sometimes other things too")
(def lang "en")
